# Generated by Django 4.0.3 on 2022-09-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.IntegerField(max_length=8)),
                ('Nombre', models.CharField(max_length=100)),
                ('Nacimiento', models.IntegerField(max_length=50)),
            ],
        ),
    ]
