# Generated by Django 4.1 on 2022-09-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='DNI',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='familiares',
            name='Nacimiento',
            field=models.IntegerField(),
        ),
    ]
