# Generated by Django 4.1 on 2022-09-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_familiares_dni_alter_familiares_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiares',
            old_name='Nacimiento',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='familiares',
            name='Nombre',
        ),
        migrations.AddField(
            model_name='familiares',
            name='nombre',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
